project_id = "fwldvvcoagylldceyvap"

[functions.detect-objects]
verify_jwt = false

[functions.ask-ai]
verify_jwt = false

[functions.embed-document]
verify_jwt = false

[functions.seed-knowledge]
verify_jwt = false